### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by iLuckyStar** [oostap/2358#5]
Остап, привет!
За пару дней пользования программой, столкнулся с некоторыми недочётами.
Да, программа только начала развиваться и с основной задачей справляется на ура, но находятся мелкие недочеты, которые ты уберешь в два счёта.

- Глюки отображения при смене ориентации экрана. Перестает работать верхний ряд кнопок, пропадает стакан, спасает переход в активность настройки/перезапуск приложения. (см. 1.mp4)

- При "лишних" символах в токене подключения, программа начинает: жрать трафик как не в себя (в первой части видео видно что потребление порядка ~157кб, при корректном значении траффик падает до вменяемых 4-8кб) +лаги и в то-же время в "Диагностике" ошибки нет. (см. 2.mp4 )

- Периодически слетает отображение в шторке (разные вариации), причем, когда такое случается, с вероятностью 80% перестают обновляться котировки. (см. фото, на месте пустоты, были трейлинги)

- При выставлении заявки с tt (трейлинг тэйк) и работающем автотазике/вечном (возможно это не связано), цена позиции с трейлингом замораживается, цена доходит до тп, ордер не выставляется, трейлинг вслед за ценой не подтягивается.

- Поправь если не прав. При срабатывании ордера на продажу из тазика, новый ордер на покупку не создастся, пока не будут учтены шесть условий, но бывает случается так, что до этого момента не доходит. Бумага продаётся, а приложение по прежнему считает что тейк не сработал и висит флаг блокировки. Можно сделать доп настройку частоты опроса? _У меня часто такое бывает, что после срабатывания тейка, приложение еще длительное время думает что ордер еще не отработал_

- П.С. Огромная просьба реализовать импорт/экспорт настроек (во время поиска багов/игры с настройками, часто приходится делать сброс и много параметров заново настраивать). _*В качестве бонуса - это позволит начать использование что-то вроде профилей, пока ты не введешь подобный функционал в приложении_.

- П.С.С. Сделать защиту от дурака, ограничив возможность выбора положительных чисел "просадки", автоматически трансформировать в отрицательное, или предупреждать об этом инфоокном.

![Screenshot_20210721_103304_com project ti2358](https://user-images.githubusercontent.com/32835132/126488998-a2d8e7bf-71c1-4059-8e05-c4e2f4dde085.jpg)

https://user-images.githubusercontent.com/32835132/126489024-e41380f6-7a26-465c-b631-2b0213ca37d4.mp4

https://user-images.githubusercontent.com/32835132/126489091-8663b5f0-6da0-4de1-b87e-37cc07fa7b11.mp4

**Comment by iLuckyStar** [comment]
- Не фиксируется цена ручного ввода в поле для изменения процентов лимитного ордера.

- Не обновляется состояние блокировки бумаг в активити "депозит", реакции на кнопку обновить нет, только если перейти на активность "заявки". Через стакан ведет себя нормально.

> Остап, скажите, в планах ли у вас поработать над этим и не баг ли это?
> 
> Сделать проверку соединения на предмет отвала сокетов с последующим самовосстановлением подключения и/или информированием о том, что за 30-60 сек не поступали новые данные.
> Заметил что в периоды высокой активности, брокер видимо прекращает лить данные и приложение перестает обновлять котировки, тазики не льются.

Зафиксировал "отвал" соединения. На видео видно что данные "подвисли" и не обновляются по принудительному запросу.

https://user-images.githubusercontent.com/32835132/126625930-7e397bd4-c6bb-425c-b2f1-dad69f63d628.mp4

**Comment by iLuckyStar** [comment]
@oostap Привет!
Подскажи куда копать. Задача оптимизировать и контролировать процесс ордеров на продажу.
Что происходит: покупается бумага, ставится ордер, а далее возможно: тупка Тинька (пролёт метеорита на околоземной орбите, кто-то не с той ноги встал), выставляется ордер только на продажу части бумаг, далее, эта часть успешно продается, оставшаяся же часть висит в портфеле. Это очень критично (цена может уйти вниз в любой момент, либо кто-то заметит когда уже придется резать крупных лосей).
Ордера на продажу нет, новый не создается, а программа продолжает думать, что она продает.
Скрины прилагаю.
Позволь я буду к тебе обращаться в ПМ?
![Screenshot_20210726_104811](https://user-images.githubusercontent.com/32835132/126955889-55e0692e-cd25-4a2e-aa3c-ae07d9238220.jpg)
![Screenshot_20210726_104819_ru tinkoff investing](https://user-images.githubusercontent.com/32835132/126956193-ee61f0a9-8e0c-44dd-a6e8-a51bacebc81f.jpg)
![Screenshot_20210726_104833_ru tinkoff investing](https://user-images.githubusercontent.com/32835132/126956084-50ec730f-c0c5-4618-9326-04f5e9cf8234.jpg)

**Comment by oostap** [comment]
@iLuckyStar привет, да, давай в ЛС со скринами и примерами, разберёмся )
